// ============================================================================
// ELITE Platform — Core Data Models
// ============================================================================

// ----------------------------------------------------------------------------
// Shared / Utility Types
// ----------------------------------------------------------------------------

/** Generic option shape used by select menus, filters, and command palettes. */
export interface Option {
  label: string;
  value: string;
  icon?: React.ComponentType<{ className?: string }>;
  withCount?: boolean;
}

// ----------------------------------------------------------------------------
// Enums & Union Types
// ----------------------------------------------------------------------------

/**
 * Approval lifecycle for developer profiles.
 *
 * - `pending`  — Submitted, awaiting admin review.
 * - `approved` — Cleared by an admin; visible on the public platform.
 * - `rejected` — Declined by an admin; hidden from all public views.
 */
export type ApprovalStatus = 'pending' | 'approved' | 'rejected';

// ----------------------------------------------------------------------------
// Social Links
// ----------------------------------------------------------------------------

/** Optional external profile links attached to a developer. */
export interface SocialLinks {
  /** GitHub profile URL. */
  github?: string;
  /** LinkedIn profile URL. */
  linkedin?: string;
  /** Personal portfolio / website URL. */
  portfolio?: string;
  /** Twitter (X) profile URL. */
  twitter?: string;
}

// ----------------------------------------------------------------------------
// Developer Profile
// ----------------------------------------------------------------------------

/**
 * Canonical representation of a developer on the ELITE platform.
 *
 * This interface is the single source of truth consumed by every feature:
 * public showcase, developer grid, individual profiles, and the admin gate.
 */
export interface DeveloperProfile {
  /** Unique identifier (UUID) generated by the database. */
  id: string;

  /** URL-safe unique handle used for public profile routing (e.g. `/dev/alex-chen`). */
  username: string;

  /** Developer's full display name. */
  fullName: string;

  /** Professional title or role (e.g. "AI Engineer", "Staff Frontend Developer"). */
  title: string;

  /** URL to the cropped, circular avatar image. */
  avatarUrl: string;

  /** Free-form biography — unrestricted length. */
  bio: string;

  /** Dynamic list of technical skills and competencies. */
  skills: string[];

  /** External profile links (GitHub, LinkedIn, portfolio, Twitter). */
  socialLinks: SocialLinks;

  /** Current admin-gate approval state. */
  status: ApprovalStatus;

  /** ISO-8601 timestamp of profile creation. */
  createdAt: string;

  /** ISO-8601 timestamp of the most recent profile update. */
  updatedAt: string;

  /** Optional list of projects owned by this developer. */
  projects?: Project[];
}

// ----------------------------------------------------------------------------
// Project
// ----------------------------------------------------------------------------

/**
 * A single portfolio project belonging to a developer.
 *
 * Each project links back to its owner via `developerId` and carries
 * its own visual asset, description, and tech-stack metadata.
 */
export interface Project {
  /** Unique identifier (UUID) for this project. */
  id: string;

  /** Foreign key → `DeveloperProfile.id`. */
  ownerId?: string;

  /** Alias key for foreign key to align with static portfolioData. */
  developerId?: string;

  /** Project display title. */
  title: string;

  /** Detailed description of the project. */
  description: string;

  /** URLs to the project showcase images. */
  imageUrl?: string | string[];
  
  /** Array of all image URLs for the gallery. */
  imageUrls?: string[];

  /** Technologies and frameworks used. */
  techStack?: string[];

  /** Optional live demo URL. */
  liveUrl?: string;

  /** Optional source-code repository URL. */
  repoUrl?: string;

  /** ISO-8601 timestamp of project creation. */
  createdAt?: string;

  /** ISO-8601 timestamp of the most recent project update. */
  updatedAt?: string;



  /** Whether this project is only visible on the creator's profile. */
  personalProfileOnly?: boolean;

  /** Co-authors/contributors of this project. */
  contributors?: any[];
}

// ----------------------------------------------------------------------------
// Admin Gate
// ----------------------------------------------------------------------------

/**
 * Payload dispatched when an admin approves or rejects a developer profile.
 *
 * Consumed exclusively by the secure Admin Gate module.
 */
export interface AdminAction {
  /** Target developer's unique identifier. */
  developerId: string;

  /** The new status to apply. */
  action: Exclude<ApprovalStatus, 'pending'>;

  /** Optional reason for rejection (required when `action` is `'rejected'`). */
  reason?: string;
}
